data_dir: ./data
output_dir: ./topic_modeling_output
stopwords_file: ./stopwords-fr.txt

chunking:
  min_chunk_size: 80
  max_chunk_size: 500
  min_tokens: 3
  method: default

embedding:
  model_name: paraphrase-multilingual-MiniLM-L12-v2

umap:
  n_neighbors: 5
  n_components: 5
  min_dist: 0.0
  metric: cosine
  random_state: 42

hdbscan:
  min_cluster_size: 7
  metric: euclidean
  cluster_selection_method: eom

vectorizer:
  min_df: 2
  ngram_range: [1, 2]
